version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
  nginx:
    image: nginx:latest
    ports:
      - "8081:8081"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf